//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.ComBoxInfo = new HashSet<ComBoxInfo>();
            this.PreBoxInfo = new HashSet<PreBoxInfo>();
        }
    
        public int postalcode { get; set; }
        public string blk { get; set; }
        public string road { get; set; }
        public string legacycode1 { get; set; }
        public string legacycode2 { get; set; }
        public string legacycode3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComBoxInfo> ComBoxInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreBoxInfo> PreBoxInfo { get; set; }
    }
}
