//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoxModelEntities : DbContext
    {
        public BoxModelEntities()
            : base("name=BoxModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ComBoxInfo> ComBoxInfoes { get; set; }
        public virtual DbSet<CommissionRecord> CommissionRecords { get; set; }
        public virtual DbSet<PreBoxInfo> PreBoxInfoes { get; set; }
        public virtual DbSet<ContactForm> ContactForms { get; set; }
    }
}
