//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComBoxInfo
    {
        public int comboxId { get; set; }
        public string rptlift { get; set; }
        public string rptcomment { get; set; }
        public string teamname { get; set; }
        public string techname { get; set; }
        public string status { get; set; }
        public string history { get; set; }
        public Nullable<int> postalcode { get; set; }
        public Nullable<int> comrecId { get; set; }
        public string lmpdnum { get; set; }
        public System.DateTime rptdate { get; set; }
        public bool ismatched { get; set; }
    
        public virtual CommissionRecord CommissionRecord { get; set; }
        public virtual Address Address { get; set; }
    }
}
