//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommissionRecord()
        {
            this.ComBoxInfoes = new HashSet<ComBoxInfo>();
        }
    
        public int comrecId { get; set; }
        public string supname { get; set; }
        public System.DateTime comrecorddate { get; set; }
        public string history { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComBoxInfo> ComBoxInfoes { get; set; }
    }
}
