//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreBoxInfo
    {
        public int preboxId { get; set; }
        public string lmpdnum { get; set; }
        public string jsonid { get; set; }
        public string checkername { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string status { get; set; }
        public string history { get; set; }
        public Nullable<bool> isdeployed { get; set; }
        public Nullable<System.DateTime> installdate { get; set; }
        public string lift { get; set; }
        public string simnum { get; set; }
        public string telco { get; set; }
        public Nullable<int> postalcode { get; set; }
        public bool ismatched { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
